services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8088:8000"

  frontend:
    build:
      context: ./web-frontend
      args:
        VITE_ENDPOINT_PREFIX: http://localhost:8088
    ports:
      - "8080:80"